-- Local compatibility baseline for legacy TeenVerse tables.
-- The historical migrations in this repository harden and extend tables that
-- already existed remotely, but were not captured as an initial migration.

create extension if not exists pgcrypto;

create table if not exists public.admins (
  id uuid primary key,
  email text,
  created_at timestamptz default now()
);

create or replace function public.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select exists (
    select 1
    from public.admins a
    where a.id = check_user_id
  );
$$;

create table if not exists public.users (
  id uuid primary key,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists public.clients (
  id uuid primary key,
  email text,
  name text,
  phone text,
  bio text,
  is_organisation text,
  is_kyc_verified boolean default false,
  kyc_status text,
  kyc_reviewed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.freelancers (
  id uuid primary key,
  email text,
  name text,
  phone text,
  nationality text,
  working_time text,
  hourly_rate numeric,
  upi text,
  projects jsonb default '[]'::jsonb,
  qualification text,
  specialty text,
  services jsonb default '[]'::jsonb,
  resume_url text,
  unlocked_skills text[] default '{}',
  parent_email text,
  bio text,
  tag_line text,
  social_links jsonb default '{}'::jsonb,
  cover_image text,
  journey_statement text,
  bank_name text,
  account_number text,
  ifsc_code text,
  age integer,
  status text default 'active',
  is_kyc_verified boolean default false,
  kyc_status text,
  current_plan text default 'Basic',
  plan_expires_at timestamptz,
  bids_remaining integer default 5,
  resumes_remaining integer default 1,
  wallet_balance numeric default 0,
  energy_points integer default 0,
  trust_score integer default 0,
  trust_score_breakdown jsonb default '[]'::jsonb,
  risk_level text default 'low',
  reputation_flag text,
  visibility_multiplier numeric default 1.00,
  bidding_restricted boolean default false,
  payout_review_required boolean default false,
  inconsistent_data_detected boolean default false,
  guardian_pan_hash text,
  account_number_hash text,
  pan_hash text,
  is_bank_linked boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.parent_otps (
  id uuid primary key default gen_random_uuid(),
  email text,
  otp_code text,
  expires_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  client_id uuid,
  title text,
  status text default 'open',
  is_elite boolean default false,
  is_archived boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint,
  freelancer_id uuid,
  freelancer_name text,
  freelancer_email text,
  client_id uuid,
  cover_letter text,
  bid_amount numeric,
  is_educational_waiver_signed boolean default false,
  status text default 'Pending',
  ai_check_status text,
  ai_checked_at timestamptz,
  paid_at timestamptz,
  completed_at timestamptz,
  submitted_at timestamptz,
  started_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.badges (
  name text primary key,
  category text,
  icon text,
  created_at timestamptz default now()
);

create table if not exists public.user_badges (
  user_id uuid,
  badge_name text,
  created_at timestamptz default now(),
  primary key (user_id, badge_name)
);

create table if not exists public.academy_quizzes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now()
);

create table if not exists public.ai_usage_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  amount numeric default 0,
  transaction_type text,
  description text,
  reference_app_id bigint,
  original_transaction_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.user_banking (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.payment_logs (
  id uuid primary key default gen_random_uuid(),
  order_id text,
  amount numeric default 0,
  status text,
  raw_data jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text,
  actor_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  status text default 'open',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid,
  sender_id uuid,
  is_admin boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid,
  receiver_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.resume_experiences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  title text,
  company text,
  description text,
  start_date date,
  end_date date,
  is_verified boolean default false,
  source text default 'manual',
  proof_status text default 'unverified',
  proof_metadata jsonb default '{}'::jsonb,
  proof_domain text,
  validation_http_status integer,
  flagged_reason text,
  risk_level text default 'low',
  platform_application_id bigint,
  created_at timestamptz default now()
);

create table if not exists public.resume_skills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  skill_name text,
  source text default 'manual',
  proof_status text default 'unverified',
  proof_metadata jsonb default '{}'::jsonb,
  verification_id uuid,
  flagged_reason text,
  is_verified boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.resume_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  title text,
  description text,
  source text default 'manual',
  proof_status text default 'unverified',
  proof_metadata jsonb default '{}'::jsonb,
  flagged_reason text,
  risk_level text default 'low',
  verified boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.user_skill_scores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  skill text,
  score integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.portfolio_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.resumes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  freelancer_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.escrow_orders (
  id uuid primary key default gen_random_uuid(),
  client_id uuid,
  freelancer_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid,
  reported_user_id uuid,
  status text default 'pending',
  created_at timestamptz default now()
);

create or replace function public.sync_kyc_status()
returns trigger
language plpgsql
as $$
begin
  return new;
end;
$$;

create or replace function public.protect_kyc_status()
returns trigger
language plpgsql
as $$
begin
  return new;
end;
$$;

create or replace function public.award_kyc_badge()
returns trigger
language plpgsql
as $$
begin
  return new;
end;
$$;
