create table if not exists public.energy_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.freelancers(id) on delete cascade,
  reward_type text not null,
  context text not null default 'default',
  amount integer not null check (amount > 0 and amount <= 100),
  claimed_at timestamptz not null default now(),
  unique (user_id, reward_type, context)
);

alter table public.energy_reward_claims enable row level security;

revoke all on public.energy_reward_claims from anon, authenticated;
grant select on public.energy_reward_claims to authenticated;

drop policy if exists "Users can view own energy reward claims" on public.energy_reward_claims;
create policy "Users can view own energy reward claims"
on public.energy_reward_claims
for select
to authenticated
using ((select auth.uid()) = user_id);

drop function if exists public.claim_daily_reward(uuid, date);

create or replace function public.claim_daily_reward(p_user_id uuid, p_today date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_amount integer := 10;
  v_inserted boolean := false;
begin
  if (select auth.uid()) is null or (select auth.uid()) <> p_user_id then
    raise exception 'Unauthorized reward claim.';
  end if;

  insert into public.energy_reward_claims (user_id, reward_type, context, amount)
  values (p_user_id, 'daily_reward', p_today::text, v_amount)
  on conflict (user_id, reward_type, context) do nothing
  returning true into v_inserted;

  if not coalesce(v_inserted, false) then
    return jsonb_build_object('success', false, 'amount', 0, 'reason', 'already_claimed');
  end if;

  update public.freelancers
  set energy_points = coalesce(energy_points, 0) + v_amount,
      last_login_date = p_today
  where id = p_user_id;

  return jsonb_build_object('success', true, 'amount', v_amount);
end;
$$;

revoke all on function public.claim_daily_reward(uuid, date) from public, anon, authenticated;
grant execute on function public.claim_daily_reward(uuid, date) to authenticated;

create or replace function public.claim_energy_reward(
  p_user_id uuid,
  p_reward_type text,
  p_context text default 'default'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.freelancers%rowtype;
  v_reward_type text := lower(trim(coalesce(p_reward_type, '')));
  v_context text := coalesce(nullif(trim(p_context), ''), 'default');
  v_amount integer;
  v_inserted boolean := false;
begin
  if (select auth.uid()) is null or (select auth.uid()) <> p_user_id then
    raise exception 'Unauthorized reward claim.';
  end if;

  select *
  into v_profile
  from public.freelancers
  where id = p_user_id
  for update;

  if v_profile.id is null then
    raise exception 'Freelancer profile not found.';
  end if;

  case v_reward_type
    when 'profile_complete' then
      v_context := 'default';
      v_amount := 10;

      if nullif(trim(coalesce(v_profile.qualification, '')), '') is null
         or nullif(trim(coalesce(v_profile.specialty, '')), '') is null
         or coalesce(v_profile.hourly_rate, 0) <= 0 then
        raise exception 'Complete profile details before claiming this reward.';
      end if;

    when 'secret_badge' then
      v_amount := case v_context
        when 'Night Owl' then 15
        when 'Weekend Warrior' then 20
        when 'Early Adopter' then 50
        else null
      end;

      if v_amount is null then
        raise exception 'Unknown badge reward.';
      end if;

      if not exists (
        select 1
        from public.user_badges
        where user_id = p_user_id
          and badge_name = v_context
      ) then
        raise exception 'Badge must be unlocked before claiming this reward.';
      end if;

    when 'quiz_general' then
      v_amount := 2;

    when 'skill_certified' then
      v_amount := 5;

      if not coalesce(v_profile.unlocked_skills, '[]'::jsonb) ? v_context then
        raise exception 'Skill must be unlocked before claiming this reward.';
      end if;

    else
      raise exception 'Unknown reward type.';
  end case;

  insert into public.energy_reward_claims (user_id, reward_type, context, amount)
  values (p_user_id, v_reward_type, v_context, v_amount)
  on conflict (user_id, reward_type, context) do nothing
  returning true into v_inserted;

  if not coalesce(v_inserted, false) then
    return jsonb_build_object('success', false, 'amount', 0, 'reason', 'already_claimed');
  end if;

  update public.freelancers
  set energy_points = coalesce(energy_points, 0) + v_amount
  where id = p_user_id;

  return jsonb_build_object('success', true, 'amount', v_amount);
end;
$$;

revoke all on function public.claim_energy_reward(uuid, text, text) from public, anon, authenticated;
grant execute on function public.claim_energy_reward(uuid, text, text) to authenticated;
