alter table public.notifications enable row level security;

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  fcm_token text not null unique,
  user_agent text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists push_tokens_user_id_idx
  on public.push_tokens (user_id)
  where revoked_at is null;

alter table public.push_tokens enable row level security;

drop policy if exists "Users can view their own push tokens" on public.push_tokens;
create policy "Users can view their own push tokens"
  on public.push_tokens
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can register their own push tokens" on public.push_tokens;
create policy "Users can register their own push tokens"
  on public.push_tokens
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can refresh their own push tokens" on public.push_tokens;
create policy "Users can refresh their own push tokens"
  on public.push_tokens
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "Users can remove their own push tokens" on public.push_tokens;
create policy "Users can remove their own push tokens"
  on public.push_tokens
  for delete
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can read their own notifications" on public.notifications;
create policy "Users can read their own notifications"
  on public.notifications
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can clear their own notifications" on public.notifications;
create policy "Users can clear their own notifications"
  on public.notifications
  for delete
  to authenticated
  using (user_id = auth.uid());

create or replace function public.notify_freelancers_of_new_job()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, message)
  select
    freelancers.id,
    'New job available: ' || coalesce(new.title, 'Untitled project')
  from public.freelancers
  where freelancers.id is not null;

  return new;
end;
$$;

revoke all on function public.notify_freelancers_of_new_job() from public, anon, authenticated;

create or replace function public.notify_client_of_new_application()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  job_title text;
begin
  select title into job_title
  from public.jobs
  where id = new.job_id;

  if new.client_id is not null then
    insert into public.notifications (user_id, message)
    values (
      new.client_id,
      'New application: ' || coalesce(job_title, 'Your project')
    );
  end if;

  return new;
end;
$$;

revoke all on function public.notify_client_of_new_application() from public, anon, authenticated;

create or replace function public.notify_freelancer_of_application_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  job_title text;
begin
  if old.status is not distinct from new.status then
    return new;
  end if;

  select title into job_title
  from public.jobs
  where id = new.job_id;

  if new.freelancer_id is not null then
    insert into public.notifications (user_id, message)
    values (
      new.freelancer_id,
      'Application ' || coalesce(new.status, 'updated') || ': ' || coalesce(job_title, 'Your project')
    );
  end if;

  return new;
end;
$$;

revoke all on function public.notify_freelancer_of_application_status() from public, anon, authenticated;

drop trigger if exists jobs_notify_freelancers_after_insert on public.jobs;
create trigger jobs_notify_freelancers_after_insert
  after insert on public.jobs
  for each row
  execute function public.notify_freelancers_of_new_job();

drop trigger if exists applications_notify_client_after_insert on public.applications;
create trigger applications_notify_client_after_insert
  after insert on public.applications
  for each row
  execute function public.notify_client_of_new_application();

drop trigger if exists applications_notify_freelancer_after_status_update on public.applications;
create trigger applications_notify_freelancer_after_status_update
  after update of status on public.applications
  for each row
  execute function public.notify_freelancer_of_application_status();

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.jobs;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
